pipeline {
    parameters {
        string(name: 'name', defaultValue: 'new_iam_user', description: 'IAM User Name')
        string(name: 'email', defaultValue: 'user@example.com', description: 'User Email Address')
    }

    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('Terraform Init') {
            steps {
                script {
                    sh 'pwd;cd Project-3/'
                    sh 'terraform init' 
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                script {
                     sh 'pwd; cd Project-3/'
                    sh 'terraform plan -var="name=${params.name}" -var="email=${params.email}"'  
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                script {
                    sh 'pwd;cd Project-3/'
                    sh 'terraform apply -auto-approve -var="name=${params.name}" -var="email=${params.email}"'  
                }
            }
        }
    }

}